
private["_filter"];
_filter = [_this,0,0,[0]] call BIS_fnc_param;
//Classname, Custom Display name (use nil for Cfg->DisplayName, price

//Shop Title Name
ctrlSetText[3103,"Cobra's Clothing Store"];

switch (_filter) do
{
	//Uniforms
	case 0:
	{
		[
		["xmas_santa_blufor_uniform",nil,500],
		["xmas_santa_ind_uniform",nil,500],
		["xmas_santa_opfor_uniform",nil,500],
		//end
		["ALRPJeff",nil,50],
		["ALRPPopcoin",nil,50],
		["ALRPbeware",nil,50],
		["ALRP911",nil,50],
		["ALRPTrump",nil,50],
		["ALRPRules",nil,50],
		["ALRPRemember",nil,50],
		["ALRPVape",nil,50],
		["ALRPBantu",nil,50],
		["ALRPHarambe",nil,50],
		["alrppugs",nil,50],
		["alrppugsnotdrugs",nil,50],
		["alrpbarney",nil,50],
		["alrpcobra",nil,50],
		["ALRPCulyer",nil,50],
		["alrpcow",nil,50],
		["alrpdrinkdriver",nil,50],
		["alrpfetus",nil,50],
		["alrpfour",nil,50],
		["alrpguilt",nil,50],
		["alrpbond",nil,50],
		["alrpleon",nil,50],
		["alrpllama",nil,50],
		["alrpmoose",nil,50],
		["alrpnandos",nil,50],
		["alrppedo",nil,50],
		["alrppostman",nil,50],
		["alrppringle",nil,50],
		["alrpputin",nil,50],
		["alrpsuit",nil,50],
		["alrpsuperman",nil,50],
		["alrpwithstupid",nil,50],
		["KAEL_SUITS_BR_F12",nil,175],
		["A3L_Suit_Uniform","Suit",135],
		["KAEL_SUITS_BR_F",nil,135],
		["KAEL_SUITS_BR_F3",nil,135],
		["KAEL_SUITS_BR_F4",nil,135],
		["KAEL_SUITS_BR_F5",nil,135],
		["KAEL_SUITS_BR_F6",nil,135],
		["KAEL_SUITS_BR_F7",nil,135],
		["KAEL_SUITS_BR_F8",nil,135],
		["KAEL_SUITS_BR_F9",nil,135],
		["KAEL_SUITS_BR_F10",nil,135],
		["KAEL_SUITS_BR_F11",nil,135],
		["KAEL_SUITS_BR_F13",nil,135],
		["KAEL_SUITS_BR_F14",nil,135],

		["TRYK_SUITS_BLK_F","TRYK Black Suit",135],
		["TRYK_SUITS_BR_F","TRYK Brown Suit",135],
     
		["cg_et1",nil,50],
		["cg_hand1",nil,50],
		["cg_illuminati1",nil,50],
		["cg_steam1",nil,50],
		["cg_stoned1",nil,50],
		["cg_taylorswift1",nil,50],

		["cg_chickens1",nil,50],
		["cg_upyours1",nil,50],
		["cg_woods1",nil,50],
		["cg_strippers1",nil,50],
		["cg_mayan1",nil,50],
		["cg_hearts1",nil,50],
		["cg_deeznuts1",nil,50],
		["cg_dad1",nil,50],
		["cg_awesome1",nil,50],
		["cg_turtles1",nil,50],
		["cg_pika1",nil,50],
		["cg_masterrace1",nil,50],
		["cg_lsd1",nil,50],
		["cg_lambo1",nil,50],
		["cg_kfc1",nil,50],
		["cg_gamerepeat1",nil,50],
		["cg_homer1",nil,50],
		["cg_gameover1",nil,50],
		["cg_fightclub1",nil,50],
		["cg_ferrari1",nil,50],
		["cg_ea1",nil,50],
		["cg_pepsi1",nil,50],
		["cg_mario1",nil,50],
		["cg_lego1",nil,50],
		["cg_burgerking1",nil,50],
		["cg_beats1",nil,50],




//koil added
		["TRYK_U_B_PCUODHs",nil,250],
		["TRYK_U_B_PCUGHs",nil,250],
		["TRYK_U_B_PCUHs",nil,250],

		["TRYK_U_B_BLOD_T","Black T Green P",50],
		["TRYK_U_B_BLKTAN_CombatUniform","Black T Tan P",70],
		["TRYK_U_B_BLKTANR_CombatUniformTshirt","Black T Tan P II",70],
		["TRYK_U_B_BLTAN_T","Black T Dark Tan P",50],
		["TRYK_U_B_fleece_UCP","Leader",50],
		["TRYK_U_B_ODTANR_CombatUniformTshirt","Green T Tan P",80],
		["TRYK_U_B_PCUGs_OD","Jeans Green Hood",80],
		["TRYK_U_B_PCUGs_gry","Jeans Gray Hood ",80],
		["TRYK_U_B_PCUGs_BLK","Jeans Black Hood",80],
		["TRYK_U_B_C02_Tsirt","Baggy Jeans + Black T",50],
		["TRYK_OVERALL_SAGE_BLKboots_nk","Coveralls Green",40],
		["TRYK_OVERALL_nok_flesh","Coveralls Tan",40],
		["TRYK_U_B_wh_blk_Rollup_CombatUniform","White T Black Cargos",70],
		["TRYK_U_B_wh_tan_Rollup_CombatUniform","White T Tan Cargos",70],
		["TRYK_U_pad_hood_Blk","Black Hood Tan Cargos",10],
		["TRYK_U_denim_hood_blk","Black Hood Jeans II",15],
		["TRYK_U_denim_jersey_blk","Black T & Jeans",10],
		["TRYK_U_denim_jersey_blu","Blue T & Jeans",10],
		["TRYK_U_denim_hood_nc","Green Hood & Jeans",10],
		["TRYK_U_taki_wh","Tan Mid East",10],
		["TRYK_U_taki_BLK","Black Mid East",10],
		["TRYK_U_taki_COY","Brown Mid East ",10],

		["TRYK_U_B_BLK_T_BK","Black Jeans (Black)",50],
		["TRYK_U_B_BLK_T_WH","Black Jeans (White)",50],
		["TRYK_U_B_Denim_T_BK","Grey Jeans (Black)",50],
		["TRYK_U_B_Denim_T_WH","Grey Jeans (White)",50],
//koil added

		["A3L_Priest_Uniform","Priest Uniform",10],
		["A3L_Character_Uniform","Life Uniform",15],
		["A3L_Dude_Outfit","Dude outfit",200],
		["A3L_Farmer_Outfit","Farmer Outfit",200],
		["A3L_Worker_Outfit","Worker Outfit",200],
		["pervt_uni","Pervert Shirt",175],
		["BluePlaid_uni","A3L Plaid (Blue)",125],
		["OrangePlaid_uni","A3L Plaid (Orange)",35],
		["PinkPlaid_uni","A3L Plaid (Pink)",35],
		["RedPlaid_uni","A3L Plaid (Red)",35],
		["YellowPlaid_uni","A3L Plaid (Yellow)",35],
		["checkered_uni","A3L Polo (Checkered)",35],
		["GbGyBr_uni","A3L Polo (GB-GY-BR)",35],
		["GnBlBr_uni","A3L Polo (GN-BL-BR)",35],
		["GnGyBr_uni","A3L Polo (GN-GN-GY)",35],
		["GyBlBr_uni","A3L Polo (GY-BL-BR)",35],
		["kingfish_uni","A3L Polo (Kingfish)",35],
		["mothertrucker_uni","A3L Polo (Mothertrucker)",35],
		["OrBlBr_uni","A3L Polo (OR-BL-BR)",35],
		["OrGnGy_uni","A3L Polo (OR-GN-GY)",35],
		["OrGyBr_uni","A3L Polo (OR-GY-BR)",35],
		["PkGnGy_uni","A3L Polo (PK-GN-GY)",35],
		["PkGyBr_uni","A3L Polo (PK-GY-BR)",35],
		["RdBlBr_uni","A3L Polo (RD-BL-BR)",35],
		["RdGnGy_uni","A3L Polo (RD-GN-GY)",35],
		["RdGyBr_uni","A3L Polo (RD-GY-BR)",35],
		["sohoku_uni","A3L Polo (Sohoku)",35],
		["WhBlBr_uni","A3L Polo (WH-BL-BR)",35],
		["WhGyBr_uni","A3L Polo (WH-GY-BR)",35],
		["YlBlBr_uni","A3L Polo (YL-BL-BR)",35],
		["YlGnGy_unI","A3L Polo (YL-GN-GY)",35],
		["YlGyBr_uni","A3L Polo (YL-GY-BR)",35],
		["racer_uni","A3L Racer Uniform",35],
		["taxi_uni","A3L Taxi Uniform",35],
		["A3L_SpookyMummy","Mummy",400],
		["A3L_Bikini_Girl","Bikini",400],
		["U_C_Scientist","Hazmat Suit",3000]		
		];
	};
	
	//Hats
	case 1:
	{
		[
			["Kio_Santa_Hat","Santa Hat", 100],
			["santahat","Santa hat",100],
			["Gorb_SantaHat",nil,100],
			["Gorb_SantaHat_Green",nil,100],
			["Masque_Santa",nil,100],
			["Gorb_RoughSantaClaus1",nil,100],
			["Gorb_RoughSantaClaus2",nil,100],
			["Gorb_RoughSantaClaus3",nil,100],
			["Gorb_Santa_White",nil,100],
			["Gorb_Santa_Tan",nil,100],
			["Gorb_Santa_Black",nil,100],
			//
			["Gorb_PuddingMask1",nil,100],
			["Gorb_PuddingMask2",nil,100],
			["Gorb_CoolElfMask1",nil,100],
			["Gorb_CoolElfMask2",nil,100],
			["Gorb_CoolElfMask3",nil,100],
			["Gorb_FestiveHat1",nil,100],
			["Gorb_FestiveHat2",nil,100],
			["Gorb_FestiveHat3",nil,100],
			["Gorb_FestiveHat4",nil,100],
			["Gorb_FestiveHat5",nil,100],
			["Gorb_FestiveHat6",nil,100],
			["Gorb_FestiveHat7",nil,100],
			["Gorb_FestiveHat8",nil,100],
			["Gorb_HolidayBaseballHat1",nil,100],
			["Gorb_HolidayBaseballHat2",nil,100],
			["Gorb_HolidayBaseballHat3",nil,100],
			["Gorb_HolidayBaseballHat4",nil,100],
			["Gorb_HolidayBaseballHat5",nil,100],
			["Gorb_HolidayBaseballHat6",nil,100],
			["Gorb_HolidayBaseballHat7",nil,100],
			["Gorb_HolidayBaseballHat8",nil,100],
			//
			["Gorb_PlaidHat1",nil,100],
			["Gorb_PlaidHat2",nil,100],
			["Gorb_PlaidHat3",nil,100],
			["Gorb_PlaidHat4",nil,100],
			["Gorb_KnittedHat1",nil,100],
			["Gorb_KnittedHat2",nil,100],
			["Gorb_KnittedHat3",nil,100],
			["Gorb_KnittedHat4",nil,100],
			////
			["Gorb_MrsClaus1",nil,100],
			["Gorb_MrsClaus2",nil,100],
			["Gorb_MrsClaus3",nil,100],
			["Gorb_UglyMrsClaus1",nil,100],
			["Gorb_UglyMrsClaus2",nil,100],
			["Gorb_UglyMrsClaus3",nil,100],
			//
			["Gorb_TurkeyMask1",nil,100],
			["Gorb_TurkeyMask2",nil,100],
			["Gorb_TurkeyMask3",nil,100],
//////////////////////////////////////////////////////
			["JM_SteveHead",nil,600],
			["JM_Zombie",nil,600],
			["JM_Cow",nil,600],
			["JM_Creeper",nil,600],
			["JM_Pig",nil,600],
			["JM_Slime",nil,600],
			["JM_Spider",nil,600],
			["JM_Clone",nil,600],
			["JM_Deadmau5",nil,600],
			["JM_Football",nil,600],
			["JM_KFC",nil,600],
			["JM_Party",nil,600],
			["JM_Wizard",nil,600],
			//NEW
			["JM_Yoshi",nil,600],
			["JM_Luigi",nil,600],
			["JM_Mario",nil,600],
			["JM_Heavy",nil,600],
			
			["JM_Doggo1",nil,600],
			["JM_Doggo3",nil,600],
			["JM_Doggo4",nil,600],
			["JM_Doggo6",nil,600],
			["JM_Doggo5",nil,600],
			["JM_Doggo",nil,600],
			["JM_Doggo2",nil,600],
			["JM_Goat",nil,600],
			["JM_sheep",nil,600],
			["JM_Chicken",nil,600],
			["JM_Spiderman",nil,600],
			["JM_wig1",nil,600],
			//end of new memes
			["Masque_Bush",nil,100],
			["Masque_Dallas",nil,100],
			["Masque_Clover",nil,100],
			["Masque_Clinton",nil,100],
			["Masque_Lincoln",nil,100],
			["Masque_Lion",nil,100],
			["Masque_Macrilleuse",nil,100],
			["Masque_Mark",nil,100],
			["Masque_Metalhead",nil,100],
			["Masque_forceAlpha",nil,100],
			["Masque_Incendiaire",nil,100],
			["Masque_Hockey",nil,100],
			["Masque_Mempo",nil,100],
			["Masque_Hockey",nil,100],
			["Masque_GdG",nil,100],
			["Masque_Aubrey",nil,100],
			["Masque_Chuck",nil,100],
			["Masque_Alien1",nil,100],
			["cg_dinomask_r",nil,150],
			["cg_dinomask_p",nil,150],
			["cg_dinomask",nil,150],
			["cg_horsehead",nil,150],
			["cg_horsehead_2",nil,150],
			["cg_horsehead_blk",nil,150],
			["cg_horsehead_pnk",nil,150],
			["ALE_H_NewEra_Monster",nil,150],
			["ALE_H_NewEra_Rouge",nil,150],
			["ALE_H_NewEra_Superman",nil,150],
			["ALE_H_NewEra_Cyan",nil,150],
			["ALE_H_NewEra_Black",nil,150],
			["ALE_H_NewEra_Lakers",nil,150],
			["ALE_H_NewEra_Redsox",nil,150],
			["ALE_H_Calot",nil,120],
			["ALE_H_Cowboy_White",nil,120],
			["ALE_H_Cowboy_Black",nil,120],
			["ALE_H_Cowboy_Brown",nil,120],
            ["kio_vfv_mask","Anon", 10],
            ["Kio_Capital_Hat","Top Hat w/Monacle", 10],
            ["a3l_hardhat","Hard Hat", 200],
            ["Kio_Afro_Hat","Brown Afro", 200],
            ["H_Beret_blk","Black Beret", 200],
            ["H_Booniehat_khk",nil, 40],
            ["H_Booniehat_oli",nil, 40],
            ["H_Booniehat_tan",nil, 40],
			["TRYK_H_Booniehat_CC",nil, 40],
            ["TRYK_H_Booniehat_AOR2",nil, 40],
            ["TRYK_H_Booniehat_3CD",nil, 40],
			["TRYK_H_Booniehat_MARPAT_WOOD",nil, 40],
            ["TRYK_H_Booniehat_JSDF",nil, 40],
            ["TRYK_H_Booniehat_WOOD",nil, 40],
            ["Kio_No1_Hat",nil, 200],
			["Masque_archNemesis",nil, 2000],
			["Masque_Fish",nil, 100],
			["Masque_Optimiste",nil, 9000],
			["Masque_Religieuse",nil, 500],
			["Masque_Smiley",nil, 3000],
			["Masque_speedRunner",nil, 3000],
			["Masque_Unic",nil, 3000],
		    ["Kio_Pirate_Hat","Pirate Hat", 10],
            ["Kio_Spinning_Hat","Spinning Hat", 200],
            ["Kio_Hat","Cute Warm Hat", 200],
            ["TRYK_H_Bandana_H","Ninja Bandana",10],
            ["TRYK_H_Bandana_wig","Ninja Bandana II",200],
            ["TRYK_H_EARMUFF","Ear Protectors",200],
            ["TRYK_H_headsetcap_blk","Black Hat",10],
            ["TRYK_H_headsetcap","White Hat",10],
            ["TRYK_H_pakol2","Mid East Hat",10],
            ["TRYK_R_CAP_BLK","Reverse Black",10],
            ["TRYK_R_CAP_TAN","Reverse White",10],
            ["TRYK_H_wig","Real Hair Wig",200],
            ["TRYK_H_woolhat","Slick Beanie",400],
			["A3L_Legoman","Lego Helmet",500],
			["A3L_soa_helmet","Biker Helmet",40],	
			["A3L_gangster_hat","Gangster Mask",10],
			["A3L_Mask","Mask",10],				
			["A3L_longhairblack","Long Hair Black",120],
			["A3L_longhairblond","Long Hair Blond",120],
			["A3L_longhairbrown","Long Hair Brown",120],
			["A3L_Crown","Crown",120],
			["cowboyhat","Cowboyhat",120],
			["A3L_mexicanhat","Mexican Hat",120],
			["A3L_Sombrero","Sombrero",120],
			["turban","Turban",120],
			["A3L_russianhat","Russianhat",120]

		];
	};
	
	//Glasses
	case 2:
	{
		[
			//beards
			["SFG_Tac_smallBeardB",nil,25],
			["SFG_Tac_smallBeardD",nil,25],
			["SFG_Tac_smallBeardG",nil,25],
			["SFG_Tac_smallBeardO",nil,25],
			["SFG_Tac_BeardB",nil,25],
			["SFG_Tac_BeardD",nil,25],
			["SFG_Tac_BeardG",nil,25],
			["SFG_Tac_BeardO",nil,25],
			["SFG_Tac_chinlessbB",nil,25],
			["SFG_Tac_chinlessbD",nil,25],
			["SFG_Tac_chinlessbG",nil,25],
			["SFG_Tac_chinlessbO",nil,25],
			["SFG_Tac_moustacheB",nil,25],
			["SFG_Tac_moustacheD",nil,25],
			["SFG_Tac_moustacheG",nil,25],
			["SFG_Tac_moustacheO",nil,25],
			["SFG_Tac_ChopsB",nil,25],
			["SFG_Tac_ChopsD",nil,25],
			["SFG_Tac_ChopsG",nil,25],
			["SFG_Tac_ChopsO",nil,25],
			["G_Shades_Black",nil,25],
			["G_Shades_Blue",nil,20],
			["G_Sport_Blackred",nil,20],
			["G_Sport_Checkered",nil,20],
			["G_Sport_Blackyellow",nil,20],
			["G_Sport_BlackWhite",nil,20],
			["G_Aviator",nil,10],
			["G_Lady_Mirror",nil,15],
			["G_Lady_Dark",nil,15],
			["G_Lady_Blue",nil,15],
			["G_Lowprofile",nil,30],
			["G_Combat",nil,55]
		];
	};
	
	//Vest
	case 3:
	{
		[
		["V_Press_F",nil,250],
		["k_cut_1",nil,255],
		["k_cut_2",nil,255],
		["k_cut_3",nil,255],
		["k_cut_4",nil,255],
		["k_cut_5",nil,255],
		["k_cut_6",nil,255],
		["k_cut_7",nil,255],
		["k_cut_8",nil,255],
		["k_cut_9",nil,255],
		["k_cut_10",nil,255],
		["k_cut_11",nil,255]
		];
	};
	
	//Backpacks
	case 4:
	{
		[
            
			["tf_anprc155",nil,500],
			["B_AssaultPack_cbr",nil,250],
			["B_AssaultPack_rgr",nil,250],
			["B_AssaultPack_khk",nil,250],
			["B_AssaultPack_sgg",nil,250],
			["B_AssaultPack_blk",nil,250],
			["B_TacticalPack_oli",nil,35],
			["B_Bergen_sgg",nil,450],
			["B_FieldPack_oli",nil,450],
			["B_FieldPack_cbr",nil,450],
			["B_FieldPack_khk",nil,450],
			["B_Carryall_oli",nil,500],
			["B_Carryall_khk",nil,500],
			["kaelmonty",nil,550],	
			["kaelmonty2",nil,550],
			["kaelmario",nil,550],	
			["kaelsuits",nil,550],	
			["koilbatman_1",nil,550],	
			["koilbender_1",nil,550],	
			["koilbender_2",nil,550],	
			["koilclint_1",nil,550],	
			["koileminem_1",nil,550],	
			["koilgraf_1",nil,550],	
			["koilgraf_2",nil,550],	
			["koilgraf_3",nil,550],	
			["koilhulk_1",nil,550],	
			["koiljoker_1",nil,550],	
			["koilpumpkin_1",nil,550],	
			["koilsparta_1",nil,550],	
			["koilsponge_1",nil,550],	
			["koilturtles_1",nil,550],	
			["koilkatie",nil,550],
			["koilpanda",nil,550],
			["koilaiden",nil,550],
			["koileagle",nil,550],
			["koilspecktators",nil,550],
			["koildarth",nil,550],
			["koilgucci",nil,550],
			["koilsmashing",nil,550],
			["koilgoonsquad",nil,550],
			["koilcat",nil,550],
			["koilbp_19",nil,550],	
			["koilbp_21",nil,550],	
			["koilbp_22",nil,550],
			["koilbp_1",nil,550],	
			["koilbp_2",nil,550],	
			["koilbp_3",nil,550],	
			["koilbp_4",nil,550],	
			["koilbp_5",nil,550],	
			["koilbp_6",nil,550],	
			["koilbp_7",nil,550],	
			["koilbp_8",nil,550],	
			["koilbp_9",nil,550],	
			["koilbp_10",nil,550],	
			["koilbp_11",nil,550],	
			["koilbp_12",nil,550],	
			["koilbp_13",nil,550],	
			["koilbp_14",nil,550],	
			["koilbp_15",nil,550],	
			["koilbp_16",nil,550],	
			["koilbp_17",nil,550],	
			["koilbp_18",nil,550]
		];
	};
};
